# -*- coding: utf-8 -*-
"""fake job.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxmct_6a6_yr8PTLJS6ErDDTd9AQ6jvo
"""

import pandas as pd
import numpy as np
import re
import nltk
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Download NLTK stopwords
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords

# Load dataset
from google.colab import files
df = pd.read_csv("/content/fake_job_postings.csv")

# Select relevant columns
df = df[['title', 'company_profile', 'description', 'requirements', 'fraudulent']]
df.fillna("", inplace=True)  # Fill missing values

# Combine text columns
df['text'] = df['title'] + " " + df['company_profile'] + " " + df['description'] + " " + df['requirements']

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Remove special characters
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])
    return text

df['text'] = df['text'].apply(preprocess_text)

# Split data
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['fraudulent'], test_size=0.2, random_state=42)

# Convert text to numerical features
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train a simple model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_vec, y_train)

# Predictions
y_pred = model.predict(X_test_vec)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Confusion Matrix
plt.figure(figsize=(6, 4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues', xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Get one real and one fake job posting
real_sample = df[df['fraudulent'] == 0].sample(1)
fake_sample = df[df['fraudulent'] == 1].sample(1)

# Display samples
print("🔹 REAL JOB POSTING SAMPLE:")
print(real_sample[['title', 'company_profile', 'description', 'requirements']])

print("\n🔹 FAKE JOB POSTING SAMPLE:")
print(fake_sample[['title', 'company_profile', 'description', 'requirements']])

real_text = real_sample['title'].values[0] + " " + real_sample['description'].values[0] + " " + real_sample['requirements'].values[0]
fake_text = fake_sample['title'].values[0] + " " + fake_sample['description'].values[0] + " " + fake_sample['requirements'].values[0]

real_pred = model.predict(vectorizer.transform([real_text]))
fake_pred = model.predict(vectorizer.transform([fake_text]))

print(f"🔹 Model Prediction for Real Job: {'FAKE' if real_pred[0] == 1 else 'REAL'}")
print(f"🔹 Model Prediction for Fake Job: {'FAKE' if fake_pred[0] == 1 else 'REAL'}")

from sklearn.feature_extraction.text import TfidfVectorizer

# Prepare text data for prediction
real_text = real_sample['title'].values[0] + " " + real_sample['description'].values[0] + " " + real_sample['requirements'].values[0]
fake_text = fake_sample['title'].values[0] + " " + fake_sample['description'].values[0] + " " + fake_sample['requirements'].values[0]

# Convert text to TF-IDF format
real_pred = model.predict(vectorizer.transform([real_text]))
fake_pred = model.predict(vectorizer.transform([fake_text]))

# Display Predictions
print(f"🔹 Model Prediction for Real Job: {'FAKE' if real_pred[0] == 1 else 'REAL'}")
print(f"🔹 Model Prediction for Fake Job: {'FAKE' if fake_pred[0] == 1 else 'REAL'}")

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Generate Word Clouds for Real & Fake Jobs
real_words = ' '.join(df[df['fraudulent'] == 0]['text'])
fake_words = ' '.join(df[df['fraudulent'] == 1]['text'])

# Real Job Word Cloud
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.imshow(WordCloud(width=400, height=400, background_color='white').generate(real_words), interpolation='bilinear')
plt.axis('off')
plt.title("Real Job Postings")

# Fake Job Word Cloud
plt.subplot(1,2,2)
plt.imshow(WordCloud(width=400, height=400, background_color='black', colormap='Reds').generate(fake_words), interpolation='bilinear')
plt.axis('off')
plt.title("Fake Job Postings")

plt.show()

import numpy as np

# Get feature importance from the RandomForest model
feature_names = np.array(vectorizer.get_feature_names_out())
importances = model.feature_importances_

# Sort important words
indices = np.argsort(importances)[-20:]  # Top 20 important words

# Plot
plt.figure(figsize=(10,6))
plt.barh(feature_names[indices], importances[indices], color='red')
plt.xlabel("Importance Score")
plt.title("Top 20 Words Indicating Fake Jobs")
plt.show()

# Get one real and one fake job posting
real_sample = df[df['fraudulent'] == 0].sample(1)

# Display samples
print("🔹 REAL JOB POSTING SAMPLE:")
print(real_sample[['title', 'company_profile', 'description', 'requirements']])

import pickle

# Save the trained model
with open('/content/fake_job_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

# Save the vectorizer
with open('/content/tfidf_vectorizer.pkl', 'wb') as vectorizer_file:
    pickle.dump(vectorizer, vectorizer_file)

print("✅ Model and vectorizer saved successfully!")

# Load the saved model
with open('/content/fake_job_model.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

# Load the vectorizer
with open('/content/tfidf_vectorizer.pkl', 'rb') as vectorizer_file:
    loaded_vectorizer = pickle.load(vectorizer_file)

print("✅ Model and vectorizer loaded successfully!")

# Test with a sample job posting
def detect_fake_job(job_title, company_profile, description, requirements):
    text = job_title + " " + company_profile + " " + description + " " + requirements
    text_tfidf = loaded_vectorizer.transform([text])
    prediction = loaded_model.predict(text_tfidf)[0]
    return "🔹 FAKE JOB ❌" if prediction == 1 else "✅ REAL JOB ✅"

# Example usage
print(detect_fake_job("Software Engineer", "Top Tech Company", "We are hiring!", "Python, ML, 3+ years experience"))